import { BugContext, CritiqueResult, PatchProposal, RetrievalRecord } from '../types/agent';

export class DebuggerAgent {
  proposeFix(
    bugContext: BugContext,
    previousCritique?: CritiqueResult,
    round = 1,
    retrievedMemories: RetrievalRecord[] = [],
  ): PatchProposal {
    const targetFile = bugContext.filePath ?? 'unknown-file';
    const summary =
      round === 1
        ? `Proposed fix for ${targetFile}`
        : `Revised fix for ${targetFile} after critique`;

    const rationaleParts = [
      `Problem: ${bugContext.problemStatement}`,
      bugContext.errorOutput ? `Observed error: ${bugContext.errorOutput}` : undefined,
      bugContext.failingTest ? `Failing test: ${bugContext.failingTest}` : undefined,
      previousCritique ? `Addressing critique: ${previousCritique.improvementSuggestions.join(' | ')}` : undefined,
      retrievedMemories.length > 0
        ? `Retrieved memories: ${retrievedMemories.map((record) => record.summary).join(' | ')}`
        : undefined,
    ].filter(Boolean);

    return {
      summary,
      candidateContent: this.buildCandidateContent(targetFile, round, previousCritique),
      diffText: this.buildPlaceholderDiff(targetFile, round, previousCritique),
      rationale: rationaleParts.join('\n'),
      confidence: this.calculateConfidence(bugContext, previousCritique, round),
    };
  }

  private buildPlaceholderDiff(
    targetFile: string,
    round: number,
    previousCritique?: CritiqueResult,
  ): string {
    const revisionNote =
      previousCritique && previousCritique.improvementSuggestions.length > 0
        ? `// revised after critique: ${previousCritique.improvementSuggestions.join(' | ')}`
        : '// initial candidate fix generated by DebuggerAgent';

    return [
      `--- a/${targetFile}`,
      `+++ b/${targetFile}`,
      `@@`,
      `- // buggy code placeholder`,
      `+ // candidate fix attempt round ${round}`,
      `+ ${revisionNote}`,
    ].join('\n');
  }

  private buildCandidateContent(
    targetFile: string,
    round: number,
    previousCritique?: CritiqueResult,
  ): string {
    const revisionNote =
      previousCritique && previousCritique.improvementSuggestions.length > 0
        ? `Revision notes: ${previousCritique.improvementSuggestions.join(' | ')}`
        : 'Revision notes: initial candidate generated by DebuggerAgent';

    return [
      `// Candidate content for ${targetFile}`,
      `// Generated in round ${round}`,
      revisionNote,
      '',
      '// Placeholder replacement content would go here in a real patching system.',
    ].join('\n');
  }

  private calculateConfidence(
    bugContext: BugContext,
    previousCritique: CritiqueResult | undefined,
    round: number,
  ): number {
    let confidence = 0.45;

    if (bugContext.errorOutput || bugContext.failingTest) {
      confidence += 0.15;
    }

    if (bugContext.relevantCode && bugContext.relevantCode.trim().length > 0) {
      confidence += 0.1;
    }

    if (previousCritique) {
      confidence += 0.05 * Math.max(round - 1, 0);
    }

    return Math.min(confidence, 0.9);
  }
}
